# Generated by Django 3.1.5 on 2021-01-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedetail',
            name='countryCode',
        ),
    ]
