# Generated by Django 3.1.5 on 2021-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_phonedetail_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetypes',
            name='phType',
            field=models.CharField(default='Primary', max_length=20),
        ),
    ]
