# Generated by Django 3.1.5 on 2021-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210112_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetypes',
            name='phType',
            field=models.CharField(max_length=20),
        ),
    ]
