# Generated by Django 3.1.5 on 2021-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210112_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetail',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
    ]
