# Generated by Django 3.1.5 on 2021-01-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210112_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressdetail',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='addresstypes',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='phonedetail',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='phonetypes',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subscriptiondetail',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subscriptiontypes',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='_id',
            new_name='id',
        ),
    ]
