# Generated by Django 3.1.5 on 2021-01-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210116_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetail',
            name='zip4',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='addressdetail',
            name='zipCode',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
