# Generated by Django 3.1.5 on 2021-01-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210120_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontypes',
            old_name='subprice',
            new_name='subPrice',
        ),
    ]
