# Generated by Django 3.1.5 on 2021-01-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20210120_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='subscriptions',
        ),
    ]
