# Generated by Django 3.1.5 on 2021-01-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_userdetails_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='subscriptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.subscriptiondetail'),
        ),
    ]
