# Generated by Django 3.1.5 on 2021-01-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_userdetails_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetail',
            name='city',
            field=models.CharField(default='New Delhi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressdetail',
            name='state',
            field=models.CharField(default='Delhi', max_length=50),
            preserve_default=False,
        ),
    ]
