# Generated by Django 3.1.5 on 2021-01-14 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 14, 54, 13, 193157, tzinfo=utc)),
        ),
    ]
