# Generated by Django 3.1.5 on 2021-01-14 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210114_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 16, 8, 36, 223117, tzinfo=utc)),
        ),
    ]
