# Generated by Django 3.1.5 on 2021-01-18 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210116_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 17, 44, 37, 967939, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnails',
            field=models.ManyToManyField(to='Product.Thumbnail'),
        ),
    ]
