# Generated by Django 3.1.5 on 2021-01-18 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210116_1827'),
        ('Product', '0007_auto_20210118_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packageDetail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='searchCriteria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail1',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 18, 31, 31, 809036, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='shippingAdresses',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='shippingAdresses',
            field=models.ManyToManyField(to='User.AddressDetail'),
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='shippingType',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='shippingType',
            field=models.ManyToManyField(to='Product.ShippingTypes'),
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
