# Generated by Django 3.1.5 on 2021-01-18 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210118_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 18, 58, 32, 884118, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='refund_period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
