# Generated by Django 3.1.5 on 2021-01-18 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20210118_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 19, 57, 51, 446519, tzinfo=utc)),
        ),
    ]
