# Generated by Django 3.1.5 on 2021-01-20 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210118_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 16, 44, 29, 82301, tzinfo=utc)),
        ),
    ]
