# Generated by Django 3.1.5 on 2021-01-20 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20210118_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 16, 6, 47, 59927, tzinfo=utc)),
        ),
    ]
