# Generated by Django 3.1.5 on 2021-01-20 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20210120_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 17, 34, 45, 966328, tzinfo=utc)),
        ),
    ]
