# Generated by Django 3.1.5 on 2021-01-21 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20210121_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='packagedetails',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shippingtypes',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 22, 7, 47, 496608, tzinfo=utc)),
        ),
    ]
