# Generated by Django 3.1.5 on 2021-01-21 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_auto_20210121_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 22, 45, 19, 732012, tzinfo=utc)),
        ),
    ]
