# Generated by Django 3.1.5 on 2021-01-23 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_auto_20210122_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 20, 46, 8, 251975, tzinfo=utc)),
        ),
    ]
