# Generated by Django 3.1.5 on 2021-01-23 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_auto_20210123_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 20, 58, 41, 623809, tzinfo=utc)),
        ),
    ]
