# Generated by Django 3.1.5 on 2021-01-24 14:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20210124_1413'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0027_auto_20210124_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentRecieved', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('deliveryAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.addressdetail')),
                ('product', models.ManyToManyField(to='Product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 14, 46, 49, 41165, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
