# Generated by Django 3.1.5 on 2021-01-24 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20210124_1413'),
        ('Product', '0028_auto_20210124_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryPhonenumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='User.phonedetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 14, 59, 15, 357912, tzinfo=utc)),
        ),
    ]
