# Generated by Django 3.1.5 on 2021-01-24 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_auto_20210124_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 15, 12, 24, 367265, tzinfo=utc)),
        ),
    ]
