# Generated by Django 3.1.5 on 2021-01-24 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_auto_20210124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 15, 28, 40, 917722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
