# Generated by Django 3.1.5 on 2021-01-24 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_auto_20210124_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productDetails',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 15, 38, 27, 647214, tzinfo=utc)),
        ),
    ]
