# Generated by Django 3.1.5 on 2021-01-24 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_auto_20210124_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 15, 47, 49, 197383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='productDetails',
            field=models.JSONField(default={}, verbose_name=''),
        ),
    ]
