# Generated by Django 3.1.5 on 2021-02-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0038_auto_20210201_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
