# Generated by Django 3.1.5 on 2021-02-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_auto_20210214_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
