# Generated by Django 3.1.5 on 2021-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0042_auto_20210214_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
